'use strict';

document.addEventListener('DOMContentLoaded', () => {
  const activeUserCode = sessionStorage.getItem('amc_active_user_code') || '1110591592';
  const TERCEROS_KEY = `amc_terceros_db_v1_${activeUserCode}`;
  const COMPRAS_KEY = `amc_facturas_compra_db_v1_${activeUserCode}`;
  const PRODUCTOS_KEY = `amc_productos_db_v1_${activeUserCode}`;
  const PRODUCTOS_LEGACY_KEY = 'amc_productos_db_v1';
  const MOVIMIENTOS_KEY = activeUserCode === '1110591592' ? 'amc_inventario_movimientos_v1' : `amc_inventario_movimientos_v1_${activeUserCode}`;
  const SESSION_KEY = 'amc_session_v2';
  const API_BASE = 'http://localhost:3000/api';
  const $ = id => document.getElementById(id);
  const state = { tercero: null, lineas: [], productos: [] };
  const money = value => '$ ' + Math.round(Number(value) || 0).toLocaleString('es-CO');
  const number = value => Number(String(value ?? '').replace(/[^0-9,.-]/g, '').replace(/\.(?=.*\.)/g, '').replace(',', '.')) || 0;
  const escapeHtml = value => { const el = document.createElement('div'); el.textContent = String(value ?? ''); return el.innerHTML; };
  const compras = () => { try { const data = JSON.parse(localStorage.getItem(COMPRAS_KEY) || '[]'); return Array.isArray(data) ? data : []; } catch { return []; } };
  const terceros = () => { try { const data = JSON.parse(localStorage.getItem(TERCEROS_KEY) || '[]'); return Array.isArray(data) ? data : []; } catch { return []; } };
  const productos = () => { try { const raw = localStorage.getItem(PRODUCTOS_KEY) || (activeUserCode === '1110591592' ? localStorage.getItem(PRODUCTOS_LEGACY_KEY) : '[]'); const data = JSON.parse(raw || '[]'); return Array.isArray(data) ? data.filter(p => p.activo !== false) : []; } catch { return []; } };
  const normalizar = value => String(value || '').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
  const token = () => { try { return JSON.parse(sessionStorage.getItem(SESSION_KEY) || '{}').token || null; } catch { return null; } };
  async function cargarProductos() { const authToken = token(); if (authToken) { try { const response = await fetch(`${API_BASE}/productos?limit=1000&soloActivos=true`, { headers: { Authorization: `Bearer ${authToken}` } }); const data = await response.json(); if (!response.ok) throw new Error(data.message || 'No fue posible cargar el catálogo.'); state.productos = (data.productos || []).filter(p => p.activo !== false).map(p => ({ ...p, precioBase: p.precioBase ?? p.precio_base ?? 0, stockTotal: p.stockTotal ?? p.stock_total ?? 0 })); return; } catch (error) { console.warn('No fue posible cargar productos desde la base de datos; se usará el catálogo local.', error); } } state.productos = productos(); }
  const productoNombre = p => `${p.nombre || ''} · ${p.codigo || 'Sin código'}`;
  const consecutivo = () => compras().reduce((max, compra) => Math.max(max, Number(compra.consecutivo) || 0), 0) + 1;
  const fechaHoy = () => new Date().toISOString().slice(0, 10);

  function aviso(texto, tipo = 'success') { $('mensaje').innerHTML = `<div class="notice ${tipo}">${texto}</div>`; }
  function formatoConsecutivo() { $('prefijo-compra').value = `FC-${String(consecutivo()).padStart(4, '0')}`; }
  function totalLinea(linea) { const baseBruta = linea.cantidad * linea.unitario; const descuento = baseBruta * linea.descuento / 100; const base = baseBruta - descuento; const iva = base * linea.iva / 100; const retencion = base * linea.retencion / 100; return { baseBruta, descuento, base, iva, retencion, total: base + iva + retencion }; }
  function leerLinea(id) { const row = document.querySelector(`[data-linea="${id}"]`); const producto = state.productos.find(p => String(p.id) === String(row.dataset.productoId)); return { id, productoId: producto?.id || '', productoCodigo: producto?.codigo || '', productoNombre: producto?.nombre || '', destino: row.querySelector('[data-field="destino"]').value, detalle: producto ? productoNombre(producto) : '', cantidad: number(row.querySelector('[data-field="cantidad"]').value), unitario: number(row.querySelector('[data-field="unitario"]').value), descuento: number(row.querySelector('[data-field="descuento"]').value), iva: number(row.querySelector('[data-field="iva"]').value), retencion: number(row.querySelector('[data-field="retencion"]').value) }; }
  function actualizarResumen() { const values = state.lineas.map(totalLinea); const sum = field => values.reduce((n, item) => n + item[field], 0); $('total-subtotal').textContent = money(sum('base')); $('total-descuento').textContent = money(sum('descuento')); $('total-iva').textContent = money(sum('iva')); $('total-retencion').textContent = money(sum('retencion')); $('total-pagar').textContent = money(sum('total')); }
  function renderLineas() { const body = $('lineas-compra'); body.innerHTML = state.lineas.map(linea => { const calc = totalLinea(linea); const producto = state.productos.find(p => String(p.id) === String(linea.productoId)); return `<tr data-linea="${linea.id}" data-producto-id="${escapeHtml(linea.productoId || '')}"><td><select data-field="destino"><option value="INVENTARIO" ${linea.destino === 'INVENTARIO' ? 'selected' : ''}>Inventario</option><option value="COSTO" ${linea.destino === 'COSTO' ? 'selected' : ''}>Costo</option><option value="GASTO" ${linea.destino === 'GASTO' ? 'selected' : ''}>Gasto</option></select></td><td><div class="product-picker ${producto ? '' : 'invalid'}"><input data-field="detalle" value="${escapeHtml(producto ? productoNombre(producto) : '')}" placeholder="Escribe mínimo 3 caracteres o arrastra"><small>${producto ? `Código: ${escapeHtml(producto.codigo || '—')} · Activo` : 'Escribe mínimo 3 caracteres para buscar o arrastra el producto aquí'}</small><div class="product-suggestions">${state.productos.map(p => `<button type="button" data-producto="${escapeHtml(p.id)}"><strong>${escapeHtml(p.nombre)}</strong><small>${escapeHtml(p.codigo || 'Sin código')} · ${escapeHtml(p.tipo || 'PRODUCTO')} · Stock: ${Number(p.stockTotal ?? p.stock_total ?? 0)}</small></button>`).join('')}<div class="ac-empty product-empty" hidden>No se encontraron productos o servicios activos.</div></div></div></td><td><input data-field="cantidad" type="number" min="0" step="any" value="${linea.cantidad || ''}"></td><td><input data-field="unitario" inputmode="decimal" value="${linea.unitario || ''}"></td><td><input data-field="descuento" type="number" min="0" max="100" step="any" value="${linea.descuento || 0}"></td><td><select data-field="iva"><option value="0" ${linea.iva === 0 ? 'selected' : ''}>0%</option><option value="5" ${linea.iva === 5 ? 'selected' : ''}>5%</option><option value="19" ${linea.iva === 19 ? 'selected' : ''}>19%</option></select></td><td><select data-field="retencion"><option value="0" ${linea.retencion === 0 ? 'selected' : ''}>0%</option><option value="2.5" ${linea.retencion === 2.5 ? 'selected' : ''}>2.5%</option><option value="4" ${linea.retencion === 4 ? 'selected' : ''}>4%</option><option value="11" ${linea.retencion === 11 ? 'selected' : ''}>11%</option></select></td><td class="num" data-total>${money(calc.total)}</td><td><button class="delete-line" type="button" data-delete="${linea.id}" aria-label="Eliminar línea">×</button></td></tr>`; }).join('');
    body.querySelectorAll('[data-field="detalle"]').forEach(input => { const picker = input.closest('.product-picker'); const helper = input.nextElementSibling; const suggestions = helper.nextElementSibling; const actualizarSugerencias = () => { const query = normalizar(input.value); const row = input.closest('tr'); const line = state.lineas.find(item => item.id === row.dataset.linea); const productoSeleccionado = state.productos.find(item => String(item.id) === String(row.dataset.productoId)); if (productoSeleccionado && input.value !== productoNombre(productoSeleccionado)) { row.dataset.productoId = ''; line.productoId = ''; picker.classList.add('invalid'); } if (query.length < 3) { suggestions.classList.remove('show'); helper.textContent = 'Escribe mínimo 3 caracteres para buscar o arrastra el producto aquí'; return; } const coincidencias = state.productos.filter(p => normalizar(p.codigo).includes(query) || normalizar(p.nombre).includes(query)).sort((a, b) => { const aExacto = normalizar(a.codigo) === query || normalizar(a.nombre) === query; const bExacto = normalizar(b.codigo) === query || normalizar(b.nombre) === query; return Number(bExacto) - Number(aExacto); }); const idsCoincidentes = new Set(coincidencias.map(p => String(p.id))); const sinResultados = suggestions.querySelector('.product-empty'); suggestions.querySelectorAll('[data-producto]').forEach(button => { button.hidden = !idsCoincidentes.has(String(button.dataset.producto)); }); coincidencias.forEach(p => { const button = suggestions.querySelector(`[data-producto="${CSS.escape(String(p.id))}"]`); if (button) suggestions.insertBefore(button, sinResultados); }); sinResultados.hidden = coincidencias.length > 0; helper.textContent = coincidencias.length ? `${coincidencias.length} coincidencia(s). Selecciona o arrastra el producto.` : 'No hay un producto o servicio activo que coincida.'; suggestions.classList.add('show'); }; input.addEventListener('focus', actualizarSugerencias); input.addEventListener('input', actualizarSugerencias); input.addEventListener('dragover', event => { event.preventDefault(); input.classList.add('drop-target'); }); input.addEventListener('dragleave', () => input.classList.remove('drop-target')); input.addEventListener('drop', event => { event.preventDefault(); input.classList.remove('drop-target'); const id = event.dataTransfer.getData('text/plain'); const button = suggestions.querySelector(`[data-producto="${CSS.escape(id)}"]`); if (button) button.click(); }); });
    body.querySelectorAll('[data-producto]').forEach(button => { button.draggable = true; button.addEventListener('dragstart', event => event.dataTransfer.setData('text/plain', button.dataset.producto)); button.addEventListener('click', () => { const row = button.closest('tr'); const p = state.productos.find(item => String(item.id) === String(button.dataset.producto)); const line = state.lineas.find(item => item.id === row.dataset.linea); line.productoId = p.id; line.unitario = Number(p.precioBase ?? p.precio_base ?? 0); line.iva = Number(p.iva ?? 19); row.dataset.productoId = p.id; renderLineas(); actualizarResumen(); }); });
    body.querySelectorAll('input,select').forEach(input => input.addEventListener('input', () => { const row = input.closest('tr'); const index = state.lineas.findIndex(linea => linea.id === row.dataset.linea); state.lineas[index] = leerLinea(row.dataset.linea); row.querySelector('[data-total]').textContent = money(totalLinea(state.lineas[index]).total); actualizarResumen(); }));
    body.querySelectorAll('[data-delete]').forEach(button => button.addEventListener('click', () => { state.lineas = state.lineas.filter(linea => linea.id !== button.dataset.delete); renderLineas(); actualizarResumen(); }));
  }
  function agregarLinea() { state.lineas.push({ id: `L-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`, destino: 'INVENTARIO', productoId: '', detalle: '', cantidad: 1, unitario: 0, descuento: 0, iva: 19, retencion: 0 }); renderLineas(); actualizarResumen(); }
  function seleccionarTercero(tercero) { state.tercero = tercero; $('tercero-buscar').value = tercero.nombre; $('tercero-seleccionado').textContent = `${tercero.nombre} · ${tercero.documento || 'Sin documento'} · ${tercero.email || 'Sin correo'}`; $('tercero-resultados').classList.remove('show'); }
  function buscarTerceros() { const q = $('tercero-buscar').value.trim().toLowerCase(); const results = terceros().filter(tercero => !q || `${tercero.nombre} ${tercero.documento} ${tercero.email}`.toLowerCase().includes(q)).slice(0, 8); $('tercero-resultados').innerHTML = results.length ? results.map((tercero, index) => `<button type="button" data-tercero="${index}"><strong>${escapeHtml(tercero.nombre)}</strong><small>${escapeHtml(tercero.documento || 'Sin documento')} · ${escapeHtml(tercero.email || 'Sin correo')}</small></button>`).join('') : '<div class="ac-empty">No hay terceros registrados.</div>'; $('tercero-resultados').classList.toggle('show', !!q); $('tercero-resultados').querySelectorAll('[data-tercero]').forEach(button => button.addEventListener('click', () => seleccionarTercero(results[Number(button.dataset.tercero)]))); }
  function limpiar() { state.tercero = null; state.lineas = []; $('tercero-buscar').value = ''; $('tercero-seleccionado').textContent = 'Selecciona un tercero registrado.'; $('numero-proveedor').value = ''; $('observaciones').value = ''; $('fecha-compra').value = fechaHoy(); formatoConsecutivo(); agregarLinea(); $('mensaje').innerHTML = ''; }
  function guardar() { state.lineas = state.lineas.map(linea => leerLinea(linea.id)); if (!state.tercero) return aviso('Selecciona el proveedor o tercero de la compra.', 'error'); if (!$('numero-proveedor').value.trim()) return aviso('Ingresa el prefijo o número de la factura del proveedor.', 'error'); if (!state.lineas.length || state.lineas.some(linea => !linea.productoId || linea.cantidad <= 0 || linea.unitario <= 0)) return aviso('Cada línea debe tener un producto o servicio activo seleccionado, cantidad y valor unitario.', 'error'); const totals = state.lineas.map(totalLinea).reduce((out, item) => Object.fromEntries(Object.keys(out).map(key => [key, out[key] + item[key]])), { base:0, descuento:0, iva:0, retencion:0, total:0 }); const next = consecutivo(); const compra = { id:`COMP-${activeUserCode}-${String(next).padStart(4,'0')}`, consecutivo:next, numeroCompra:`FC-${String(next).padStart(4,'0')}`, numeroProveedor:$('numero-proveedor').value.trim(), fecha:$('fecha-compra').value, tercero:{ nombre:state.tercero.nombre, documento:state.tercero.documento || '', email:state.tercero.email || '' }, lineas:state.lineas.map(linea => ({ ...linea, ...totalLinea(linea) })), totales:totals, observaciones:$('observaciones').value.trim(), generadoEn:new Date().toISOString(), estado:'REGISTRADA' }; const current = compras(); current.push(compra); localStorage.setItem(COMPRAS_KEY, JSON.stringify(current)); actualizarInventario(compra); aviso('Factura de compra registrada y el inventario fue actualizado.'); window.setTimeout(() => { window.location.href = 'facturas-compra-generadas.html'; }, 500); }
  function actualizarInventario(compra) { let key = activeUserCode === '1110591592' && localStorage.getItem(PRODUCTOS_LEGACY_KEY) ? PRODUCTOS_LEGACY_KEY : PRODUCTOS_KEY; let lista; try { lista = JSON.parse(localStorage.getItem(key) || '[]'); } catch { lista = []; } let movimientos; try { movimientos = JSON.parse(localStorage.getItem(MOVIMIENTOS_KEY) || '[]'); } catch { movimientos = []; } compra.lineas.filter(l => l.destino === 'INVENTARIO').forEach(linea => { const p = lista.find(item => String(item.id) === String(linea.productoId)); if (!p) return; const anterior = Number(p.stockTotal ?? p.stock_total ?? 0) || 0; const nuevo = anterior + linea.cantidad; if ('stock_total' in p) p.stock_total = nuevo; else p.stockTotal = nuevo; movimientos.push({ id:`COMPRA-${compra.id}-${linea.id}`, producto_id:p.id, tipo:'ENTRADA_COMPRA', cantidad:linea.cantidad, stock_anterior:anterior, stock_nuevo:nuevo, referencia:compra.numeroCompra, fecha:compra.fecha, creadoEn:compra.generadoEn }); }); localStorage.setItem(key, JSON.stringify(lista)); localStorage.setItem(MOVIMIENTOS_KEY, JSON.stringify(movimientos)); }
  async function iniciar() { await cargarProductos(); $('fecha-compra').value = fechaHoy(); formatoConsecutivo(); agregarLinea(); $('tercero-buscar').addEventListener('input', buscarTerceros); $('tercero-buscar').addEventListener('focus', buscarTerceros); $('btn-agregar-linea').addEventListener('click', agregarLinea); $('btn-limpiar').addEventListener('click', limpiar); $('btn-guardar').addEventListener('click', guardar); }
  iniciar();
});
