'use strict';

document.addEventListener('DOMContentLoaded', () => {
  const activeUserCode = sessionStorage.getItem('amc_active_user_code') || '1110591592';
  const TERCEROS_KEY = `amc_terceros_db_v1_${activeUserCode}`;
  const COMPRAS_KEY = `amc_facturas_compra_db_v1_${activeUserCode}`;
  const $ = id => document.getElementById(id);
  const state = { tercero: null, lineas: [] };
  const money = value => '$ ' + Math.round(Number(value) || 0).toLocaleString('es-CO');
  const number = value => Number(String(value ?? '').replace(/[^0-9,.-]/g, '').replace(/\.(?=.*\.)/g, '').replace(',', '.')) || 0;
  const escapeHtml = value => { const el = document.createElement('div'); el.textContent = String(value ?? ''); return el.innerHTML; };
  const compras = () => { try { const data = JSON.parse(localStorage.getItem(COMPRAS_KEY) || '[]'); return Array.isArray(data) ? data : []; } catch { return []; } };
  const terceros = () => { try { const data = JSON.parse(localStorage.getItem(TERCEROS_KEY) || '[]'); return Array.isArray(data) ? data : []; } catch { return []; } };
  const consecutivo = () => compras().reduce((max, compra) => Math.max(max, Number(compra.consecutivo) || 0), 0) + 1;
  const fechaHoy = () => new Date().toISOString().slice(0, 10);

  function aviso(texto, tipo = 'success') { $('mensaje').innerHTML = `<div class="notice ${tipo}">${texto}</div>`; }
  function formatoConsecutivo() { $('prefijo-compra').value = `FC-${String(consecutivo()).padStart(4, '0')}`; }
  function totalLinea(linea) { const baseBruta = linea.cantidad * linea.unitario; const descuento = baseBruta * linea.descuento / 100; const base = baseBruta - descuento; const iva = base * linea.iva / 100; const retencion = base * linea.retencion / 100; return { baseBruta, descuento, base, iva, retencion, total: base + iva + retencion }; }
  function leerLinea(id) { const row = document.querySelector(`[data-linea="${id}"]`); return { id, destino: row.querySelector('[data-field="destino"]').value, detalle: row.querySelector('[data-field="detalle"]').value.trim(), cantidad: number(row.querySelector('[data-field="cantidad"]').value), unitario: number(row.querySelector('[data-field="unitario"]').value), descuento: number(row.querySelector('[data-field="descuento"]').value), iva: number(row.querySelector('[data-field="iva"]').value), retencion: number(row.querySelector('[data-field="retencion"]').value) }; }
  function actualizarResumen() { const values = state.lineas.map(totalLinea); const sum = field => values.reduce((n, item) => n + item[field], 0); $('total-subtotal').textContent = money(sum('base')); $('total-descuento').textContent = money(sum('descuento')); $('total-iva').textContent = money(sum('iva')); $('total-retencion').textContent = money(sum('retencion')); $('total-pagar').textContent = money(sum('total')); }
  function renderLineas() { const body = $('lineas-compra'); body.innerHTML = state.lineas.map((linea, index) => { const calc = totalLinea(linea); return `<tr data-linea="${linea.id}"><td><select data-field="destino"><option value="INVENTARIO" ${linea.destino === 'INVENTARIO' ? 'selected' : ''}>Inventario</option><option value="COSTO" ${linea.destino === 'COSTO' ? 'selected' : ''}>Costo</option><option value="GASTO" ${linea.destino === 'GASTO' ? 'selected' : ''}>Gasto</option></select></td><td><input data-field="detalle" value="${escapeHtml(linea.detalle)}" placeholder="Producto, servicio o gasto"></td><td><input data-field="cantidad" type="number" min="0" step="any" value="${linea.cantidad || ''}"></td><td><input data-field="unitario" inputmode="decimal" value="${linea.unitario || ''}"></td><td><input data-field="descuento" type="number" min="0" max="100" step="any" value="${linea.descuento || 0}"></td><td><select data-field="iva"><option value="0" ${linea.iva === 0 ? 'selected' : ''}>0%</option><option value="5" ${linea.iva === 5 ? 'selected' : ''}>5%</option><option value="19" ${linea.iva === 19 ? 'selected' : ''}>19%</option></select></td><td><select data-field="retencion"><option value="0" ${linea.retencion === 0 ? 'selected' : ''}>0%</option><option value="2.5" ${linea.retencion === 2.5 ? 'selected' : ''}>2.5%</option><option value="4" ${linea.retencion === 4 ? 'selected' : ''}>4%</option><option value="11" ${linea.retencion === 11 ? 'selected' : ''}>11%</option></select></td><td class="num" data-total>${money(calc.total)}</td><td><button class="delete-line" type="button" data-delete="${linea.id}" aria-label="Eliminar línea">×</button></td></tr>`; }).join('');
    body.querySelectorAll('input,select').forEach(input => input.addEventListener('input', () => { const row = input.closest('tr'); const index = state.lineas.findIndex(linea => linea.id === row.dataset.linea); state.lineas[index] = leerLinea(row.dataset.linea); row.querySelector('[data-total]').textContent = money(totalLinea(state.lineas[index]).total); actualizarResumen(); }));
    body.querySelectorAll('[data-delete]').forEach(button => button.addEventListener('click', () => { state.lineas = state.lineas.filter(linea => linea.id !== button.dataset.delete); renderLineas(); actualizarResumen(); }));
  }
  function agregarLinea() { state.lineas.push({ id: `L-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`, destino: 'GASTO', detalle: '', cantidad: 1, unitario: 0, descuento: 0, iva: 19, retencion: 0 }); renderLineas(); actualizarResumen(); }
  function seleccionarTercero(tercero) { state.tercero = tercero; $('tercero-buscar').value = tercero.nombre; $('tercero-seleccionado').textContent = `${tercero.nombre} · ${tercero.documento || 'Sin documento'} · ${tercero.email || 'Sin correo'}`; $('tercero-resultados').classList.remove('show'); }
  function buscarTerceros() { const q = $('tercero-buscar').value.trim().toLowerCase(); const results = terceros().filter(tercero => !q || `${tercero.nombre} ${tercero.documento} ${tercero.email}`.toLowerCase().includes(q)).slice(0, 8); $('tercero-resultados').innerHTML = results.length ? results.map((tercero, index) => `<button type="button" data-tercero="${index}"><strong>${escapeHtml(tercero.nombre)}</strong><small>${escapeHtml(tercero.documento || 'Sin documento')} · ${escapeHtml(tercero.email || 'Sin correo')}</small></button>`).join('') : '<div class="ac-empty">No hay terceros registrados.</div>'; $('tercero-resultados').classList.toggle('show', !!q); $('tercero-resultados').querySelectorAll('[data-tercero]').forEach(button => button.addEventListener('click', () => seleccionarTercero(results[Number(button.dataset.tercero)]))); }
  function limpiar() { state.tercero = null; state.lineas = []; $('tercero-buscar').value = ''; $('tercero-seleccionado').textContent = 'Selecciona un tercero registrado.'; $('numero-proveedor').value = ''; $('observaciones').value = ''; $('fecha-compra').value = fechaHoy(); formatoConsecutivo(); agregarLinea(); $('mensaje').innerHTML = ''; }
  function guardar() { state.lineas = state.lineas.map(linea => leerLinea(linea.id)); if (!state.tercero) return aviso('Selecciona el proveedor o tercero de la compra.', 'error'); if (!$('numero-proveedor').value.trim()) return aviso('Ingresa el prefijo o número de la factura del proveedor.', 'error'); if (!state.lineas.length || state.lineas.some(linea => !linea.detalle || linea.cantidad <= 0 || linea.unitario <= 0)) return aviso('Completa producto o detalle, cantidad y valor unitario en cada línea.', 'error'); const totals = state.lineas.map(totalLinea).reduce((out, item) => Object.fromEntries(Object.keys(out).map(key => [key, out[key] + item[key]])), { base:0, descuento:0, iva:0, retencion:0, total:0 }); const current = compras(); const next = consecutivo(); current.push({ id:`COMP-${activeUserCode}-${String(next).padStart(4,'0')}`, consecutivo:next, numeroCompra:`FC-${String(next).padStart(4,'0')}`, numeroProveedor:$('numero-proveedor').value.trim(), fecha:$('fecha-compra').value, tercero:{ nombre:state.tercero.nombre, documento:state.tercero.documento || '', email:state.tercero.email || '' }, lineas:state.lineas.map(linea => ({ ...linea, ...totalLinea(linea) })), totales:totals, observaciones:$('observaciones').value.trim(), generadoEn:new Date().toISOString(), estado:'REGISTRADA' }); localStorage.setItem(COMPRAS_KEY, JSON.stringify(current)); aviso('Factura de compra registrada correctamente.'); window.setTimeout(() => { window.location.href = 'facturas-compra-generadas.html'; }, 500); }
  $('fecha-compra').value = fechaHoy(); formatoConsecutivo(); agregarLinea(); $('tercero-buscar').addEventListener('input', buscarTerceros); $('tercero-buscar').addEventListener('focus', buscarTerceros); $('btn-agregar-linea').addEventListener('click', agregarLinea); $('btn-limpiar').addEventListener('click', limpiar); $('btn-guardar').addEventListener('click', guardar);
});
